// Save-code words for the Academy: exactly 1,024, so four of them give 1,024^4 (about 1.1 trillion) codes.
// Lowercase a to z, 3 to 8 letters. Radio, network and lab words first, then plain everyday words.
// Picked by a script that drops homophones, brand and vendor names, anything rude, plural and tense
// pairs, and any two words one letter apart. progresstest.js checks all of that again.
// CommonJS so the Worker (esbuild) and Node can both load it. Only new codes are drawn from this list;
// an existing code is looked up by its hash, so changing the list later never breaks a code.
module.exports = [
  "antenna", "beacon", "fresnel", "yagi", "lobe", "dipole", "preamble", "trunk", "sector", "omni", "carrier", "phasor",
  "frame", "packet", "header", "retry", "backoff", "slot", "beam", "mesh", "portal", "uplink", "switch", "router",
  "port", "cable", "fiber", "copper", "rack", "console", "shell", "subnet", "gateway", "bridge", "lease", "metric",
  "hop", "ping", "trace", "probe", "roam", "radio", "signal", "noise", "fade", "gain", "margin", "budget",
  "decibel", "band", "width", "guard", "pilot", "parity", "cipher", "token", "nonce", "tunnel", "overlay", "underlay",
  "spine", "leaf", "fabric", "stack", "chassis", "module", "optic", "laser", "photon", "lens", "prism", "mirror",
  "scatter", "refract", "absorb", "volt", "joule", "kelvin", "coil", "ferrite", "balun", "coax", "feeder", "mast",
  "tripod", "bracket", "mount", "tilt", "azimuth", "compass", "heading", "matrix", "stream", "spatial", "lattice", "sample",
  "filter", "mixer", "tuner", "crystal", "clock", "jitter", "latency", "delay", "burst", "pulse", "chirp", "sweep",
  "spectrum", "scope", "gauge", "survey", "heatmap", "plenum", "riser", "closet", "conduit", "raceway", "keystone", "crimp",
  "splice", "label", "tester", "outlet", "socket", "breaker", "fuse", "diode", "resistor", "circuit", "wafer", "silicon",
  "solder", "pinout", "jumper", "shunt", "ground", "airflow", "intake", "exhaust", "thermal", "cooling", "supply", "battery",
  "charger", "adapter", "inverter", "surge", "brownout", "outage", "failover", "standby", "backup", "archive", "config", "profile",
  "access", "native", "lag", "storm", "flood", "prune", "core", "octet", "nibble", "field", "offset", "length",
  "segment", "session", "flow", "buffer", "shape", "class", "priority", "voice", "video", "bulk", "domain", "record",
  "resolve", "proxy", "helper", "server", "client", "host", "node", "neighbor", "area", "hello", "pacing", "prefix",
  "wildcard", "summary", "default", "static", "dynamic", "local", "global", "anycast", "unicast", "snoop", "graft", "origin",
  "path", "anchor", "cluster", "quorum", "witness", "arbiter", "replica", "shard", "index", "journal", "ledger", "syslog",
  "agent", "terminal", "kernel", "daemon", "thread", "pipe", "regex", "script", "macro", "enter", "escape", "commit",
  "rollback", "diff", "merge", "branch", "release", "build", "deploy", "canary", "rollout", "freeze", "thaw", "hash",
  "salt", "vault", "latch", "shield", "armor", "badge", "fence", "moat", "bastion", "sentry", "warden", "patrol",
  "bench", "sandbox", "rig", "fixture", "caliper", "ruler", "notebook", "logbook", "binder", "drill", "wrench", "pliers",
  "cutter", "ladder", "dolly", "crate", "tote", "drawer", "cabinet", "tray", "spool", "hook", "sticky", "steer",
  "nudge", "passkey", "airtime", "contend", "defer", "window", "fragment", "rogue", "hidden", "ducting", "ripple", "crest",
  "trough", "phase", "shift", "delta", "sigma", "theta", "gamma", "alpha", "omega", "lambda", "kappa", "radian",
  "degree", "angle", "arc", "tangent", "cosine", "polar", "orbit", "helix", "spiral", "horn", "dish", "director",
  "driven", "element", "boom", "radome", "flange", "sleeve", "collar", "clamp", "strap", "washer", "rivet", "drop",
  "pigtail", "duplex", "simplex", "channel", "dwell", "scan", "passive", "active", "handoff", "downlink", "backhaul", "amber",
  "beige", "blue", "bronze", "cedar", "cobalt", "coral", "cream", "crimson", "cyan", "denim", "ebony", "emerald",
  "gold", "green", "hazel", "indigo", "ivory", "khaki", "lemon", "lilac", "lime", "magenta", "maroon", "mauve",
  "mint", "navy", "ochre", "olive", "onyx", "orange", "peach", "purple", "ruby", "rust", "saffron", "sage",
  "salmon", "scarlet", "sepia", "sienna", "silver", "slate", "teal", "topaz", "violet", "acorn", "alpine", "aspen",
  "autumn", "bamboo", "basin", "bay", "birch", "blossom", "bluff", "boulder", "brook", "canyon", "cape", "cavern",
  "cliff", "cloud", "clover", "coast", "comet", "cypress", "daisy", "desert", "dune", "dusk", "dawn", "earth",
  "fern", "flint", "flora", "forest", "fossil", "frost", "glacier", "glade", "glen", "granite", "grove", "gulf",
  "harbor", "heath", "hedge", "hill", "hollow", "horizon", "iris", "island", "ivy", "jungle", "lagoon", "lake",
  "lava", "lichen", "lily", "lotus", "maple", "marsh", "meadow", "meteor", "moon", "moss", "mountain", "nebula",
  "oak", "oasis", "ocean", "orchid", "pebble", "petal", "planet", "pond", "poppy", "prairie", "quartz", "rainbow",
  "rapids", "reef", "shore", "sky", "snow", "spring", "spruce", "star", "stone", "summit", "sunset", "swamp",
  "thicket", "thistle", "thunder", "timber", "trail", "tulip", "tundra", "valley", "vine", "volcano", "willow", "wind",
  "winter", "zephyr", "bison", "bobcat", "coyote", "dolphin", "dove", "eagle", "egret", "elk", "falcon", "ferret",
  "finch", "fox", "gazelle", "gecko", "heron", "hawk", "ibex", "koala", "lark", "lemur", "lion", "llama",
  "lynx", "macaw", "magpie", "moose", "narwhal", "newt", "ocelot", "orca", "osprey", "otter", "owl", "panda",
  "panther", "parrot", "pelican", "penguin", "puffin", "quail", "rabbit", "raven", "robin", "sparrow", "tapir", "tiger",
  "toucan", "trout", "turtle", "walrus", "weasel", "wombat", "zebra", "bagel", "banana", "biscuit", "bread", "cabbage",
  "candy", "cashew", "celery", "cheese", "cider", "cinnamon", "cocoa", "coconut", "cookie", "cracker", "crepe", "cumin",
  "curry", "custard", "dough", "dumpling", "garlic", "ginger", "grape", "gravy", "guava", "honey", "jelly", "kale",
  "kiwi", "lentil", "mango", "melon", "nectar", "noodle", "nutmeg", "onion", "oyster", "papaya", "paprika", "pasta",
  "peanut", "pecan", "pepper", "pickle", "pizza", "potato", "pretzel", "pudding", "pumpkin", "radish", "raisin", "rice",
  "salsa", "sesame", "sorbet", "soup", "spinach", "sugar", "sushi", "taco", "tofu", "tomato", "truffle", "turnip",
  "vanilla", "waffle", "walnut", "wasabi", "yogurt", "arrow", "atlas", "banner", "barrel", "basket", "bell", "blanket",
  "bottle", "brick", "brush", "bucket", "button", "camera", "candle", "canoe", "canvas", "card", "carpet", "chair",
  "chalk", "couch", "crayon", "crown", "cup", "curtain", "dial", "domino", "door", "drum", "envelope", "feather",
  "flask", "flute", "fork", "goblet", "guitar", "hammer", "helmet", "hinge", "jar", "kettle", "kite", "lantern",
  "letter", "lever", "magnet", "map", "marble", "mitten", "mug", "napkin", "needle", "paddle", "paint", "palette",
  "paper", "pencil", "piano", "pitcher", "pulley", "puzzle", "quill", "ribbon", "rope", "rudder", "scarf", "scroll",
  "shovel", "sled", "teapot", "torch", "towel", "trophy", "trumpet", "vase", "violin", "wagon", "wallet", "wreath",
  "yarn", "zipper", "ballad", "banjo", "chorus", "harp", "melody", "opera", "rhythm", "sonata", "tempo", "viola",
  "waltz", "jazz", "polka", "sketch", "mural", "pastel", "fresco", "mosaic", "statue", "sonnet", "haiku", "legend",
  "myth", "epic", "archery", "chess", "curling", "dart", "fencing", "hockey", "javelin", "kayak", "lacrosse", "marathon",
  "polo", "puck", "rowing", "slalom", "soccer", "surf", "tennis", "yacht", "avenue", "bazaar", "cabin", "campus",
  "canal", "castle", "city", "cottage", "depot", "dock", "garage", "highway", "jetty", "kiosk", "lodge", "market",
  "museum", "palace", "plaza", "studio", "suburb", "town", "village", "wharf", "blizzard", "cyclone", "drizzle", "drought",
  "equinox", "monsoon", "season", "sleet", "solstice", "tornado", "twilight", "typhoon", "summer", "midnight", "evening", "decade",
  "century", "epoch", "moment", "minute", "month", "year", "atom", "carbon", "cosmos", "energy", "enzyme", "fusion",
  "galaxy", "gravity", "helium", "hydrogen", "isotope", "lithium", "matter", "neon", "neutron", "nickel", "nitrogen", "nucleus",
  "oxygen", "plasma", "polymer", "quantum", "quark", "sodium", "vapor", "velocity", "zinc", "argon", "boron", "xenon",
  "krypton", "tungsten", "bismuth", "gallium", "indium", "zircon", "axis", "circle", "cube", "curve", "cylinder", "digit",
  "ellipse", "factor", "fraction", "median", "oval", "polygon", "sphere", "square", "tensor", "torus", "triangle", "vertex",
  "acre", "agile", "apex", "aura", "axle", "basalt", "blaze", "bonus", "bounty", "brave", "bright", "cadet",
  "calm", "camel", "captain", "cargo", "charm", "cheer", "chief", "citrus", "clarity", "cobble", "cosmic", "cotton",
  "daring", "dynamo", "eager", "elder", "empire", "fancy", "feast", "fiesta", "flicker", "gentle", "giant", "glimmer",
  "gravel", "harvest", "hickory", "honest", "humble", "icicle", "idea", "iron", "jovial", "jubilee", "keen", "lively",
  "lucky", "lunar", "magic", "mantle", "mellow", "merit", "mighty", "modest", "monarch", "motto", "noble", "north",
  "south", "west", "novel", "nugget", "patio", "pilgrim", "pioneer", "placid", "plume", "pulsar", "quest", "quiet",
  "quiver", "regal", "relic", "remedy", "robust", "royal", "rustic", "sapphire", "satin", "scenic", "scout", "serene",
  "shadow", "silk", "sincere", "spirit", "sprout", "stable", "steady", "stellar", "sturdy", "sublime", "sunny", "superb",
  "talent", "thrive", "tonic", "tranquil", "treasure", "tribute", "trusty", "turbo", "tweed", "unity", "urban", "valiant",
  "velvet", "venture", "verdant", "vessel", "vista", "vivid", "voyage", "wander", "whimsy", "wisdom", "wizard", "zenith",
  "climb", "drift", "hover", "skim", "stride", "weave", "whirl", "cascade", "estuary", "sunrise", "aurora", "nimbus",
  "mangrove", "redwood", "magnolia", "jasmine", "lavender", "marigold", "primrose", "bluebell", "laurel", "myrtle", "peony", "dahlia",
  "zinnia", "azalea", "acacia", "banyan", "mahogany", "chestnut", "linden", "rowan", "cattail", "cactus", "agave", "yucca",
  "aloe", "alpaca", "bluejay", "buffalo", "caribou", "cheetah", "chipmunk", "condor", "dingo", "donkey", "flamingo", "giraffe",
  "gopher", "hamster", "hedgehog", "hyena", "iguana", "impala", "jackal", "kestrel", "ladybug", "leopard", "lobster", "manatee",
  "meerkat", "mongoose", "octopus", "ostrich", "pheasant", "platypus", "possum", "raccoon", "reindeer", "rhino", "sardine", "scallop",
  "seahorse", "shrimp", "skylark", "snail",
];
